// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYl0u2SpWBS3xLdd7JiTEW3TuAfdh8cTY',
    appId: '1:709337548585:web:0bab70cd8185e0ed7bd938',
    messagingSenderId: '709337548585',
    projectId: 'authentication-with-bff',
    authDomain: 'authentication-with-bff.firebaseapp.com',
    storageBucket: 'authentication-with-bff.appspot.com',
    measurementId: 'G-DN44JRSY0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekD2LgBVytQVmFYB8TaBXnzrYhxaHexQ',
    appId: '1:709337548585:android:13a5e903083709077bd938',
    messagingSenderId: '709337548585',
    projectId: 'authentication-with-bff',
    storageBucket: 'authentication-with-bff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMEGAealQlDkNSuP9auK8KyVNCiiu4e1Q',
    appId: '1:709337548585:ios:44df09597468d6727bd938',
    messagingSenderId: '709337548585',
    projectId: 'authentication-with-bff',
    storageBucket: 'authentication-with-bff.appspot.com',
    iosBundleId: 'com.example.authenticationWithBlocFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMEGAealQlDkNSuP9auK8KyVNCiiu4e1Q',
    appId: '1:709337548585:ios:44df09597468d6727bd938',
    messagingSenderId: '709337548585',
    projectId: 'authentication-with-bff',
    storageBucket: 'authentication-with-bff.appspot.com',
    iosBundleId: 'com.example.authenticationWithBlocFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYl0u2SpWBS3xLdd7JiTEW3TuAfdh8cTY',
    appId: '1:709337548585:web:4b36376b4fa7ed527bd938',
    messagingSenderId: '709337548585',
    projectId: 'authentication-with-bff',
    authDomain: 'authentication-with-bff.firebaseapp.com',
    storageBucket: 'authentication-with-bff.appspot.com',
    measurementId: 'G-V1EWQMQ7Q4',
  );
}
